spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: business
          uri: lb://business
          order: 1
          predicates:
            - Path=/business/**
          filters:
            - StripPrefix=1
        - id: system
          uri: lb://system
          order: 1
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
